---
swagger: "2.0"
info:
  title: "subsidy Allocation API"
  description: "Manage and allocate subsidies"
  version: "1.0"

host: "188.166.29.174:8080"
basePath: "/v1"

schemes:
- "http"

# security:
# - basic_auth: []

securityDefinitions:
  basic_auth:
    type: basic
  
tags:
# - name: "users"
#   description: "Create, read, update, and delete users."
- name: "master-accounts"
  description:  "Create, read, update, and delete master accounts."
- name: "citizens"
  description:  "Create, read, update, and delete citizens."
- name: "subsidies"
  description:  "Create, read, update, and delete subsidies."

paths:
  # /users:
  #   get:
  #     tags: 
  #     - "users"
  #     summary: "Returns a list of users."
  #     produces:
  #     - "application/json"
  #     responses:
  #       200:
  #         description: OK
  #         schema:
  #           type: array
  #           items:                
  #             $ref: "#/definitions/user"
  #   post:
  #     tags: 
  #     - "users"
  #     summary: "Create a new user"
  #     consumes:
  #     - "application/nl.kpmg.v1.user+json"
  #     produces: 
  #     - "application/nl.kpmg.v1.user+json"
  #     responses:
  #       201:
  #         description: Created
  #         schema:
  #           $ref: "#/definitions/user"
  #     parameters:
  #       - in: "body"
  #         name: "body"
  #         description: "user to add"
  #         required: True
  #         schema:
  #           $ref: "#/definitions/user"
                  
  # /users/{username}:
  #   get:
  #     tags: 
  #     - "users"
  #     summary: "Returns a specific user"
  #     produces:
  #     - "application/nl.kpmg.v1.user+json"
  #     responses:
  #       200:
  #         description: OK
  #         schema:
  #           $ref: "#/definitions/user"
  #     parameters: 
  #     - in: "path"
  #       name: "username"
  #       type: "string"
  #       required: true
        
  #   put:
  #     tags: 
  #     - "users"
  #     summary: "Re-upload user's information"
  #     consumes:
  #     - "application/nl.kpmg.v1.user+json"
  #     produces:
  #     - "application/nl.kpmg.v1.user+json"
  #     responses:
  #       200:
  #         description: OK
  #         schema:
  #           $ref: "#/definitions/user"
  #     parameters: 
  #     - in: "path"
  #       name: "username"
  #       type: "string"
  #       required: true
  #     - in: "body"
  #       name: "body"
  #       description: "user details"
  #       required: True
  #       schema:
  #         $ref: "#/definitions/user"

  #   patch:
  #     tags: 
  #     - "users"
  #     summary: "Edit a user's information"
  #     consumes:
  #     - "application/nl.kpmg.v1.user+json"
  #     produces:
  #     - "application/nl.kpmg.v1.user+json"
  #     responses:
  #       200:
  #         description: OK
  #         schema:
  #           $ref: "#/definitions/user"
  #     parameters: 
  #     - in: "path"
  #       name: "username"
  #       type: "string"
  #       required: true
  #     - in: "body"
  #       name: "body"
  #       description: "user properties to be updated"
  #       required: True
  #       schema:
  #         $ref: "#/definitions/user"
        
  #   delete:
  #     tags: 
  #     - "users"
  #     summary: "Remove a user"
  #     responses:
  #       200:
  #         description: OK
  #     parameters: 
  #     - in: "path"
  #       name: "username"
  #       type: "string"
  #       required: true

  /master-accounts:
    get:
      tags: 
      - "master-accounts"
      summary: "Returns a list of master-accounts."
      produces:
      - "application/json"
      responses:
        200:
          description: OK
          schema:
            type: array
            items:                
              $ref: "#/definitions/master-account-base"
              
    post:
      tags: 
      - "master-accounts"
      summary: "Create a new master-account"
      consumes:
      - "application/nl.kpmg.v1.master-account+json"
      produces: 
      - "application/nl.kpmg.v1.master-account+json"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/master-account"
      parameters:
        - in: "body"
          name: "body"
          description: "master-account to add"
          required: True
          schema:
            $ref: "#/definitions/master-account-base"
                  
  /master-accounts/{id}:
    get:
      tags: 
      - "master-accounts"
      summary: "Returns a specific master-account"
      produces:
      - "application/nl.kpmg.v1.master-account+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/master-account"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
        
    put:
      tags: 
      - "master-accounts"
      summary: "Re-upload a master-account's information"
      consumes:
      - "application/nl.kpmg.v1.master-account+json"
      produces:
      - "application/nl.kpmg.v1.master-account+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/master-account"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "master-account details"
        required: True
        schema:
          $ref: "#/definitions/master-account"
        
    patch:
      tags: 
      - "master-accounts"
      summary: "Edit a master-account's information"
      consumes:
      - "application/nl.kpmg.v1.master-account+json"
      produces:
      - "application/nl.kpmg.v1.master-account+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/master-account"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "master-account properties to be updated"
        required: True
        schema:
          $ref: "#/definitions/master-account"
        
    delete:
      tags: 
      - "master-accounts"
      summary: "Remove a master-account"
      responses:
        200:
          description: OK
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
  
  /citizens:
    get:
      tags: 
      - "citizens"
      summary: "Returns a list of citizens."
      produces:
      - "application/json"
      security: 
      - basic_auth: []
      
      responses:
        200:
          description: OK
          schema:
            type: array
            items:                
              $ref: "#/definitions/citizen-base"
        401:
          description: Unauthorized
              
    post:
      tags: 
      - "citizens"
      summary: "Create a new citizen"
      consumes:
      - "application/nl.kpmg.v1.citizen+json"
      produces: 
      - "application/nl.kpmg.v1.citizen+json"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/citizen"
      parameters:
        - in: "body"
          name: "body"
          description: "citizen to add"
          required: True
          schema:
            $ref: "#/definitions/citizen"
                  
  /citizens/{id}:
    get:
      tags: 
      - "citizens"
      summary: "Returns a specific citizen"
      produces:
      - "application/nl.kpmg.v1.citizen+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/citizen"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
        
    put:
      tags: 
      - "citizens"
      summary: "Re-upload a citizen's information"
      consumes:
      - "application/nl.kpmg.v1.citizen+json"
      produces:
      - "application/nl.kpmg.v1.citizen+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/citizen"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "citizen details"
        required: True
        schema:
          $ref: "#/definitions/citizen"
          
    patch:
      tags: 
      - "citizens"
      summary: "Edit a citizen's information"
      consumes:
      - "application/nl.kpmg.v1.citizen+json"
      produces:
      - "application/nl.kpmg.v1.citizen+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/citizen"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "citizen properties to be updated"
        required: True
        schema:
          $ref: "#/definitions/citizen"
        
    delete:
      tags: 
      - "citizens"
      summary: "Remove a citizen"
      responses:
        200:
          description: OK
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true

  /subsidies:    
    get:
      tags: 
      - "subsidies"
      summary: "Returns a list of subsidies."
      produces:
      - "application/json"
      parameters:
        - in: "query"
          name: "status"
          description: "subsidy status filter"
          required: False
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:                
              $ref: "#/definitions/subsidy-base"
        
    post:
      tags: 
      - "subsidies"
      summary: "Create a new subsidy"
      consumes:
      - "application/nl.kpmg.v1.subsidy-base+json"
      produces: 
      - "application/nl.kpmg.v1.subsidy-base+json"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/subsidy"
      parameters:
        - in: "body"
          name: "body"
          description: "subsidy to add"
          required: True
          schema:
            $ref: "#/definitions/subsidy-base"
                  
  /subsidies/{id}:
    get:
      tags: 
      - "subsidies"
      summary: "Returns a specific subsidy"
      produces:
      - "application/nl.kpmg.v1.subsidy+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/subsidy"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
        
    put:
      tags: 
      - "subsidies"
      summary: "Re-upload a subsidy's information"
      consumes:
      - "application/nl.kpmg.v1.subsidy+json"
      produces:
      - "application/nl.kpmg.v1.subsidy+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/subsidy"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "subsidy details"
        required: True
        schema:
          $ref: "#/definitions/subsidy-base"
          
    patch:
      tags: 
      - "subsidies"
      summary: "Edit a subsidy's information"
      consumes:
      - "application/nl.kpmg.v1.subsidy+json"
      produces:
      - "application/nl.kpmg.v1.subsidy+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/subsidy"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "subsidy properties to be updated"
        required: True
        schema:
          $ref: "#/definitions/subsidy-base"
        
    delete:
      tags: 
      - "subsidies"
      summary: "Remove a subsidy"
      responses:
        200:
          description: OK
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true

  /subsidies/{id}/actions/approve:
    post:
      tags: 
        - "subsidies"
      summary: "Approve a subsidy"
      consumes:
      - "application/nl.kpmg.v1.user+json"
      produces:
      - "application/nl.kpmg.v1.user+json"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/subsidy"
      parameters: 
      - in: "path"
        name: "id"
        type: "string"
        required: true
      - in: "body"
        name: "body"
        description: "user approving subsidy"
        required: True
        schema:
          $ref: "#/definitions/user"

         
definitions:
  user:
    description: "A user of the subsidy Allocation API"
    type: object
    properties:
      username:
        type: string
      real_name:
        type: string
      email:
        type: string
        format: email
      phone_number:
        type: string
        
  account-base:
    description: "A bank account"
    type: object
    properties:
      name:
        type: string
      # account_type:
      #   type: string
      description:
        type: string
      iban:
        type: string
      balance:
        type: number
  
  account:
    description: "A bank account"
    allOf: 
    - $ref: "#/definitions/account-base"
    - type: object
      properties:
        transactions:
          type: array
          items:
            $ref: "#/definitions/transaction"

  master-account-base:
    description: "A master-account-base serves as the source for a specific class of subsidy"
    allOf:
    - $ref: "#/definitions/account-base"
    - type: object
      properties:
        id: 
          type: string

  master-account:
    description: "A master-account serves as the source for a specific class of subsidy"
    allOf:
    - $ref: "#/definitions/master-account-base"
    - $ref: "#/definitions/account"
    # - type: object
    #   properties:
    #     subsidies:
    #       type: array
    #       items:
    #         $ref: "#/definitions/subsidy-base"
    #     viewers:
    #       type: array
    #       items:
    #         $ref: "#/definitions/user"
    #     admins:
    #       type: array
    #       items:
    #         $ref: "#/definitions/user"
    
    
  
  citizen-base:
    description: "A citizen of Amsterdam who may be recieving subsidies"
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
      phone_number:
        type: string


  citizen:
    description: "A citizen of Amsterdam who may be recieving subsidies"
    allOf:
    - $ref: "#/definitions/citizen-base"
    # - type: object
    #   properties:
    #     subsidies:
    #       type: array
    #       items: 
    #         $ref: "#/definitions/subsidy-base"
            
  subsidy-base:
    description: "A recurring allocation of funds made available from a master-account to a recipient citizen's account"
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      master:
        $ref: "#/definitions/master-account-base"
      recipient:
        $ref: "#/definitions/citizen-base"
      account:
        $ref: "#/definitions/account-base"
      frequency:
        type: string
        # enum:
        # - "once"
        # - "daily"
        # - "weekly"
        # - "bi-weekly"
        # - "monthly"
        # - "yearly"
      amount:
        type: number
        minimum: 0
      start_date:
        type: string
        format: date
      end_date:
        type: string
        format: date
      comment:
        type: string
      status:
        type: string
        # enum:
        # - 
        # - PENDING_APPROVAL
        # - PENDING_CONNECTION
        # - OPEN
        # - CLOSED
        # - CONNECTION_FAILED

  subsidy:
    description: "A recurring allocation of funds made available from a master-account to a recipient citizen's account"
    allOf:
      - $ref: "#/definitions/subsidy-base"
      - type: object
        properties:
          account:
            $ref: "#/definitions/account"
            
  transaction:
    type: object
    properties:
      counterparty_name:
        type: string
      counterparty_iban:
        type: string
      description:
        type: string
      amount:
        type: number
      timestamp:
        type: string
        format: date-time
      
