# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.account_base import AccountBase  # noqa: F401,E501
from swagger_server.models.transaction import Transaction  # noqa: F401,E501
from swagger_server import util


class Account(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, description: str=None, iban: str=None, balance: float=None, transactions: List[Transaction]=None):  # noqa: E501
        """Account - a model defined in Swagger

        :param name: The name of this Account.  # noqa: E501
        :type name: str
        :param description: The description of this Account.  # noqa: E501
        :type description: str
        :param iban: The iban of this Account.  # noqa: E501
        :type iban: str
        :param balance: The balance of this Account.  # noqa: E501
        :type balance: float
        :param transactions: The transactions of this Account.  # noqa: E501
        :type transactions: List[Transaction]
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'iban': str,
            'balance': float,
            'transactions': List[Transaction]
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'iban': 'iban',
            'balance': 'balance',
            'transactions': 'transactions'
        }

        self._name = name
        self._description = description
        self._iban = iban
        self._balance = balance
        self._transactions = transactions

    @classmethod
    def from_dict(cls, dikt) -> 'Account':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The account of this Account.  # noqa: E501
        :rtype: Account
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Account.


        :return: The name of this Account.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Account.


        :param name: The name of this Account.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Account.


        :return: The description of this Account.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Account.


        :param description: The description of this Account.
        :type description: str
        """

        self._description = description

    @property
    def iban(self) -> str:
        """Gets the iban of this Account.


        :return: The iban of this Account.
        :rtype: str
        """
        return self._iban

    @iban.setter
    def iban(self, iban: str):
        """Sets the iban of this Account.


        :param iban: The iban of this Account.
        :type iban: str
        """

        self._iban = iban

    @property
    def balance(self) -> float:
        """Gets the balance of this Account.


        :return: The balance of this Account.
        :rtype: float
        """
        return self._balance

    @balance.setter
    def balance(self, balance: float):
        """Sets the balance of this Account.


        :param balance: The balance of this Account.
        :type balance: float
        """

        self._balance = balance

    @property
    def transactions(self) -> List[Transaction]:
        """Gets the transactions of this Account.


        :return: The transactions of this Account.
        :rtype: List[Transaction]
        """
        return self._transactions

    @transactions.setter
    def transactions(self, transactions: List[Transaction]):
        """Sets the transactions of this Account.


        :param transactions: The transactions of this Account.
        :type transactions: List[Transaction]
        """

        self._transactions = transactions
