# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CitizenBase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: float=None, real_name: str=None):  # noqa: E501
        """CitizenBase - a model defined in Swagger

        :param id: The id of this CitizenBase.  # noqa: E501
        :type id: float
        :param real_name: The real_name of this CitizenBase.  # noqa: E501
        :type real_name: str
        """
        self.swagger_types = {
            'id': float,
            'real_name': str
        }

        self.attribute_map = {
            'id': 'id',
            'real_name': 'realName'
        }

        self._id = id
        self._real_name = real_name

    @classmethod
    def from_dict(cls, dikt) -> 'CitizenBase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The citizen-base of this CitizenBase.  # noqa: E501
        :rtype: CitizenBase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> float:
        """Gets the id of this CitizenBase.


        :return: The id of this CitizenBase.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """Sets the id of this CitizenBase.


        :param id: The id of this CitizenBase.
        :type id: float
        """

        self._id = id

    @property
    def real_name(self) -> str:
        """Gets the real_name of this CitizenBase.


        :return: The real_name of this CitizenBase.
        :rtype: str
        """
        return self._real_name

    @real_name.setter
    def real_name(self, real_name: str):
        """Sets the real_name of this CitizenBase.


        :param real_name: The real_name of this CitizenBase.
        :type real_name: str
        """

        self._real_name = real_name
