# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CitizenBase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, email: str=None, phone_number: str=None):  # noqa: E501
        """CitizenBase - a model defined in Swagger

        :param id: The id of this CitizenBase.  # noqa: E501
        :type id: str
        :param name: The name of this CitizenBase.  # noqa: E501
        :type name: str
        :param email: The email of this CitizenBase.  # noqa: E501
        :type email: str
        :param phone_number: The phone_number of this CitizenBase.  # noqa: E501
        :type phone_number: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'email': str,
            'phone_number': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'email': 'email',
            'phone_number': 'phone_number'
        }

        self._id = id
        self._name = name
        self._email = email
        self._phone_number = phone_number

    @classmethod
    def from_dict(cls, dikt) -> 'CitizenBase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The citizen-base of this CitizenBase.  # noqa: E501
        :rtype: CitizenBase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this CitizenBase.


        :return: The id of this CitizenBase.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CitizenBase.


        :param id: The id of this CitizenBase.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this CitizenBase.


        :return: The name of this CitizenBase.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CitizenBase.


        :param name: The name of this CitizenBase.
        :type name: str
        """

        self._name = name

    @property
    def email(self) -> str:
        """Gets the email of this CitizenBase.


        :return: The email of this CitizenBase.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this CitizenBase.


        :param email: The email of this CitizenBase.
        :type email: str
        """

        self._email = email

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this CitizenBase.


        :return: The phone_number of this CitizenBase.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this CitizenBase.


        :param phone_number: The phone_number of this CitizenBase.
        :type phone_number: str
        """

        self._phone_number = phone_number
