# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.citizen_base import CitizenBase  # noqa: F401,E501
from swagger_server.models.subsidy_base import SubsidyBase  # noqa: F401,E501
from swagger_server import util


class Citizen(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, real_name: str=None, email: str=None, phone_number: str=None, mutation_pending: bool=True, subsidies: List[SubsidyBase]=None):  # noqa: E501
        """Citizen - a model defined in Swagger

        :param id: The id of this Citizen.  # noqa: E501
        :type id: str
        :param real_name: The real_name of this Citizen.  # noqa: E501
        :type real_name: str
        :param email: The email of this Citizen.  # noqa: E501
        :type email: str
        :param phone_number: The phone_number of this Citizen.  # noqa: E501
        :type phone_number: str
        :param mutation_pending: The mutation_pending of this Citizen.  # noqa: E501
        :type mutation_pending: bool
        :param subsidies: The subsidies of this Citizen.  # noqa: E501
        :type subsidies: List[SubsidyBase]
        """
        self.swagger_types = {
            'id': str,
            'real_name': str,
            'email': str,
            'phone_number': str,
            'mutation_pending': bool,
            'subsidies': List[SubsidyBase]
        }

        self.attribute_map = {
            'id': 'id',
            'real_name': 'real_name',
            'email': 'email',
            'phone_number': 'phone_number',
            'mutation_pending': 'mutation_pending',
            'subsidies': 'subsidies'
        }

        self._id = id
        self._real_name = real_name
        self._email = email
        self._phone_number = phone_number
        self._mutation_pending = mutation_pending
        self._subsidies = subsidies

    @classmethod
    def from_dict(cls, dikt) -> 'Citizen':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The citizen of this Citizen.  # noqa: E501
        :rtype: Citizen
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Citizen.


        :return: The id of this Citizen.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Citizen.


        :param id: The id of this Citizen.
        :type id: str
        """

        self._id = id

    @property
    def real_name(self) -> str:
        """Gets the real_name of this Citizen.


        :return: The real_name of this Citizen.
        :rtype: str
        """
        return self._real_name

    @real_name.setter
    def real_name(self, real_name: str):
        """Sets the real_name of this Citizen.


        :param real_name: The real_name of this Citizen.
        :type real_name: str
        """

        self._real_name = real_name

    @property
    def email(self) -> str:
        """Gets the email of this Citizen.


        :return: The email of this Citizen.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Citizen.


        :param email: The email of this Citizen.
        :type email: str
        """

        self._email = email

    @property
    def phone_number(self) -> str:
        """Gets the phone_number of this Citizen.


        :return: The phone_number of this Citizen.
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number: str):
        """Sets the phone_number of this Citizen.


        :param phone_number: The phone_number of this Citizen.
        :type phone_number: str
        """

        self._phone_number = phone_number

    @property
    def mutation_pending(self) -> bool:
        """Gets the mutation_pending of this Citizen.


        :return: The mutation_pending of this Citizen.
        :rtype: bool
        """
        return self._mutation_pending

    @mutation_pending.setter
    def mutation_pending(self, mutation_pending: bool):
        """Sets the mutation_pending of this Citizen.


        :param mutation_pending: The mutation_pending of this Citizen.
        :type mutation_pending: bool
        """

        self._mutation_pending = mutation_pending

    @property
    def subsidies(self) -> List[SubsidyBase]:
        """Gets the subsidies of this Citizen.


        :return: The subsidies of this Citizen.
        :rtype: List[SubsidyBase]
        """
        return self._subsidies

    @subsidies.setter
    def subsidies(self, subsidies: List[SubsidyBase]):
        """Sets the subsidies of this Citizen.


        :param subsidies: The subsidies of this Citizen.
        :type subsidies: List[SubsidyBase]
        """

        self._subsidies = subsidies
