# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.status_base import StatusBase  # noqa: F401,E501
from swagger_server import util


class EndpointStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, url: str=None, active: bool=None):  # noqa: E501
        """EndpointStatus - a model defined in Swagger

        :param name: The name of this EndpointStatus.  # noqa: E501
        :type name: str
        :param url: The url of this EndpointStatus.  # noqa: E501
        :type url: str
        :param active: The active of this EndpointStatus.  # noqa: E501
        :type active: bool
        """
        self.swagger_types = {
            'name': str,
            'url': str,
            'active': bool
        }

        self.attribute_map = {
            'name': 'name',
            'url': 'url',
            'active': 'active'
        }

        self._name = name
        self._url = url
        self._active = active

    @classmethod
    def from_dict(cls, dikt) -> 'EndpointStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The endpoint-status of this EndpointStatus.  # noqa: E501
        :rtype: EndpointStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this EndpointStatus.


        :return: The name of this EndpointStatus.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this EndpointStatus.


        :param name: The name of this EndpointStatus.
        :type name: str
        """

        self._name = name

    @property
    def url(self) -> str:
        """Gets the url of this EndpointStatus.


        :return: The url of this EndpointStatus.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this EndpointStatus.


        :param url: The url of this EndpointStatus.
        :type url: str
        """

        self._url = url

    @property
    def active(self) -> bool:
        """Gets the active of this EndpointStatus.


        :return: The active of this EndpointStatus.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this EndpointStatus.


        :param active: The active of this EndpointStatus.
        :type active: bool
        """

        self._active = active
