# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Initiative(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, default: bool=None):  # noqa: E501
        """Initiative - a model defined in Swagger

        :param name: The name of this Initiative.  # noqa: E501
        :type name: str
        :param default: The default of this Initiative.  # noqa: E501
        :type default: bool
        """
        self.swagger_types = {
            'name': str,
            'default': bool
        }

        self.attribute_map = {
            'name': 'name',
            'default': 'default'
        }

        self._name = name
        self._default = default

    @classmethod
    def from_dict(cls, dikt) -> 'Initiative':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The initiative of this Initiative.  # noqa: E501
        :rtype: Initiative
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Initiative.


        :return: The name of this Initiative.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Initiative.


        :param name: The name of this Initiative.
        :type name: str
        """

        self._name = name

    @property
    def default(self) -> bool:
        """Gets the default of this Initiative.


        :return: The default of this Initiative.
        :rtype: bool
        """
        return self._default

    @default.setter
    def default(self, default: bool):
        """Sets the default of this Initiative.


        :param default: The default of this Initiative.
        :type default: bool
        """

        self._default = default
