# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.account import Account  # noqa: F401,E501
from swagger_server import util


class MasterAccountBase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, account_type: str=None, iban: str=None, balance: float=0.0):  # noqa: E501
        """MasterAccountBase - a model defined in Swagger

        :param name: The name of this MasterAccountBase.  # noqa: E501
        :type name: str
        :param account_type: The account_type of this MasterAccountBase.  # noqa: E501
        :type account_type: str
        :param iban: The iban of this MasterAccountBase.  # noqa: E501
        :type iban: str
        :param balance: The balance of this MasterAccountBase.  # noqa: E501
        :type balance: float
        """
        self.swagger_types = {
            'name': str,
            'account_type': str,
            'iban': str,
            'balance': float
        }

        self.attribute_map = {
            'name': 'name',
            'account_type': 'account_type',
            'iban': 'iban',
            'balance': 'balance'
        }

        self._name = name
        self._account_type = account_type
        self._iban = iban
        self._balance = balance

    @classmethod
    def from_dict(cls, dikt) -> 'MasterAccountBase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The master-account-base of this MasterAccountBase.  # noqa: E501
        :rtype: MasterAccountBase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MasterAccountBase.


        :return: The name of this MasterAccountBase.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MasterAccountBase.


        :param name: The name of this MasterAccountBase.
        :type name: str
        """

        self._name = name

    @property
    def account_type(self) -> str:
        """Gets the account_type of this MasterAccountBase.


        :return: The account_type of this MasterAccountBase.
        :rtype: str
        """
        return self._account_type

    @account_type.setter
    def account_type(self, account_type: str):
        """Sets the account_type of this MasterAccountBase.


        :param account_type: The account_type of this MasterAccountBase.
        :type account_type: str
        """

        self._account_type = account_type

    @property
    def iban(self) -> str:
        """Gets the iban of this MasterAccountBase.


        :return: The iban of this MasterAccountBase.
        :rtype: str
        """
        return self._iban

    @iban.setter
    def iban(self, iban: str):
        """Sets the iban of this MasterAccountBase.


        :param iban: The iban of this MasterAccountBase.
        :type iban: str
        """

        self._iban = iban

    @property
    def balance(self) -> float:
        """Gets the balance of this MasterAccountBase.


        :return: The balance of this MasterAccountBase.
        :rtype: float
        """
        return self._balance

    @balance.setter
    def balance(self, balance: float):
        """Sets the balance of this MasterAccountBase.


        :param balance: The balance of this MasterAccountBase.
        :type balance: float
        """

        self._balance = balance
