# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.account_base import AccountBase  # noqa: F401,E501
from swagger_server import util


class MasterAccountBase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, description: str=None, iban: str=None, balance: float=None, id: str=None):  # noqa: E501
        """MasterAccountBase - a model defined in Swagger

        :param name: The name of this MasterAccountBase.  # noqa: E501
        :type name: str
        :param description: The description of this MasterAccountBase.  # noqa: E501
        :type description: str
        :param iban: The iban of this MasterAccountBase.  # noqa: E501
        :type iban: str
        :param balance: The balance of this MasterAccountBase.  # noqa: E501
        :type balance: float
        :param id: The id of this MasterAccountBase.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'name': str,
            'description': str,
            'iban': str,
            'balance': float,
            'id': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'iban': 'iban',
            'balance': 'balance',
            'id': 'id'
        }

        self._name = name
        self._description = description
        self._iban = iban
        self._balance = balance
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'MasterAccountBase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The master-account-base of this MasterAccountBase.  # noqa: E501
        :rtype: MasterAccountBase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this MasterAccountBase.


        :return: The name of this MasterAccountBase.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MasterAccountBase.


        :param name: The name of this MasterAccountBase.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this MasterAccountBase.


        :return: The description of this MasterAccountBase.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this MasterAccountBase.


        :param description: The description of this MasterAccountBase.
        :type description: str
        """

        self._description = description

    @property
    def iban(self) -> str:
        """Gets the iban of this MasterAccountBase.


        :return: The iban of this MasterAccountBase.
        :rtype: str
        """
        return self._iban

    @iban.setter
    def iban(self, iban: str):
        """Sets the iban of this MasterAccountBase.


        :param iban: The iban of this MasterAccountBase.
        :type iban: str
        """

        self._iban = iban

    @property
    def balance(self) -> float:
        """Gets the balance of this MasterAccountBase.


        :return: The balance of this MasterAccountBase.
        :rtype: float
        """
        return self._balance

    @balance.setter
    def balance(self, balance: float):
        """Sets the balance of this MasterAccountBase.


        :param balance: The balance of this MasterAccountBase.
        :type balance: float
        """
        if balance is not None and balance < 0:  # noqa: E501
            raise ValueError("Invalid value for `balance`, must be a value greater than or equal to `0`")  # noqa: E501

        self._balance = balance

    @property
    def id(self) -> str:
        """Gets the id of this MasterAccountBase.


        :return: The id of this MasterAccountBase.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this MasterAccountBase.


        :param id: The id of this MasterAccountBase.
        :type id: str
        """

        self._id = id
