# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.subsidy_base import SubsidyBase  # noqa: F401,E501
from swagger_server import util


class SubsidylogitemMutation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, _from: SubsidyBase=None, to: SubsidyBase=None):  # noqa: E501
        """SubsidylogitemMutation - a model defined in Swagger

        :param _from: The _from of this SubsidylogitemMutation.  # noqa: E501
        :type _from: SubsidyBase
        :param to: The to of this SubsidylogitemMutation.  # noqa: E501
        :type to: SubsidyBase
        """
        self.swagger_types = {
            '_from': SubsidyBase,
            'to': SubsidyBase
        }

        self.attribute_map = {
            '_from': 'from',
            'to': 'to'
        }

        self.__from = _from
        self._to = to

    @classmethod
    def from_dict(cls, dikt) -> 'SubsidylogitemMutation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The subsidylogitem_mutation of this SubsidylogitemMutation.  # noqa: E501
        :rtype: SubsidylogitemMutation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _from(self) -> SubsidyBase:
        """Gets the _from of this SubsidylogitemMutation.


        :return: The _from of this SubsidylogitemMutation.
        :rtype: SubsidyBase
        """
        return self.__from

    @_from.setter
    def _from(self, _from: SubsidyBase):
        """Sets the _from of this SubsidylogitemMutation.


        :param _from: The _from of this SubsidylogitemMutation.
        :type _from: SubsidyBase
        """

        self.__from = _from

    @property
    def to(self) -> SubsidyBase:
        """Gets the to of this SubsidylogitemMutation.


        :return: The to of this SubsidylogitemMutation.
        :rtype: SubsidyBase
        """
        return self._to

    @to.setter
    def to(self, to: SubsidyBase):
        """Sets the to of this SubsidylogitemMutation.


        :param to: The to of this SubsidylogitemMutation.
        :type to: SubsidyBase
        """

        self._to = to
