# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.account_base import AccountBase  # noqa: F401,E501
from swagger_server.models.citizen_base import CitizenBase  # noqa: F401,E501
from swagger_server.models.master_account_base import MasterAccountBase  # noqa: F401,E501
from swagger_server.models.subsidy_base import SubsidyBase  # noqa: F401,E501
from swagger_server import util


class Subsidy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, master: MasterAccountBase=None, recipient: CitizenBase=None, account: AccountBase=None, frequency: str=None, amount: float=None, startdate: date=None, enddate: date=None, comment: str=None):  # noqa: E501
        """Subsidy - a model defined in Swagger

        :param id: The id of this Subsidy.  # noqa: E501
        :type id: str
        :param name: The name of this Subsidy.  # noqa: E501
        :type name: str
        :param master: The master of this Subsidy.  # noqa: E501
        :type master: MasterAccountBase
        :param recipient: The recipient of this Subsidy.  # noqa: E501
        :type recipient: CitizenBase
        :param account: The account of this Subsidy.  # noqa: E501
        :type account: AccountBase
        :param frequency: The frequency of this Subsidy.  # noqa: E501
        :type frequency: str
        :param amount: The amount of this Subsidy.  # noqa: E501
        :type amount: float
        :param startdate: The startdate of this Subsidy.  # noqa: E501
        :type startdate: date
        :param enddate: The enddate of this Subsidy.  # noqa: E501
        :type enddate: date
        :param comment: The comment of this Subsidy.  # noqa: E501
        :type comment: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'master': MasterAccountBase,
            'recipient': CitizenBase,
            'account': AccountBase,
            'frequency': str,
            'amount': float,
            'startdate': date,
            'enddate': date,
            'comment': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'master': 'master',
            'recipient': 'recipient',
            'account': 'account',
            'frequency': 'frequency',
            'amount': 'amount',
            'startdate': 'startdate',
            'enddate': 'enddate',
            'comment': 'comment'
        }

        self._id = id
        self._name = name
        self._master = master
        self._recipient = recipient
        self._account = account
        self._frequency = frequency
        self._amount = amount
        self._startdate = startdate
        self._enddate = enddate
        self._comment = comment

    @classmethod
    def from_dict(cls, dikt) -> 'Subsidy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The subsidy of this Subsidy.  # noqa: E501
        :rtype: Subsidy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Subsidy.


        :return: The id of this Subsidy.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Subsidy.


        :param id: The id of this Subsidy.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Subsidy.


        :return: The name of this Subsidy.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Subsidy.


        :param name: The name of this Subsidy.
        :type name: str
        """

        self._name = name

    @property
    def master(self) -> MasterAccountBase:
        """Gets the master of this Subsidy.


        :return: The master of this Subsidy.
        :rtype: MasterAccountBase
        """
        return self._master

    @master.setter
    def master(self, master: MasterAccountBase):
        """Sets the master of this Subsidy.


        :param master: The master of this Subsidy.
        :type master: MasterAccountBase
        """

        self._master = master

    @property
    def recipient(self) -> CitizenBase:
        """Gets the recipient of this Subsidy.


        :return: The recipient of this Subsidy.
        :rtype: CitizenBase
        """
        return self._recipient

    @recipient.setter
    def recipient(self, recipient: CitizenBase):
        """Sets the recipient of this Subsidy.


        :param recipient: The recipient of this Subsidy.
        :type recipient: CitizenBase
        """

        self._recipient = recipient

    @property
    def account(self) -> AccountBase:
        """Gets the account of this Subsidy.


        :return: The account of this Subsidy.
        :rtype: AccountBase
        """
        return self._account

    @account.setter
    def account(self, account: AccountBase):
        """Sets the account of this Subsidy.


        :param account: The account of this Subsidy.
        :type account: AccountBase
        """

        self._account = account

    @property
    def frequency(self) -> str:
        """Gets the frequency of this Subsidy.


        :return: The frequency of this Subsidy.
        :rtype: str
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: str):
        """Sets the frequency of this Subsidy.


        :param frequency: The frequency of this Subsidy.
        :type frequency: str
        """

        self._frequency = frequency

    @property
    def amount(self) -> float:
        """Gets the amount of this Subsidy.


        :return: The amount of this Subsidy.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this Subsidy.


        :param amount: The amount of this Subsidy.
        :type amount: float
        """
        if amount is not None and amount < 0:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must be a value greater than or equal to `0`")  # noqa: E501

        self._amount = amount

    @property
    def startdate(self) -> date:
        """Gets the startdate of this Subsidy.


        :return: The startdate of this Subsidy.
        :rtype: date
        """
        return self._startdate

    @startdate.setter
    def startdate(self, startdate: date):
        """Sets the startdate of this Subsidy.


        :param startdate: The startdate of this Subsidy.
        :type startdate: date
        """

        self._startdate = startdate

    @property
    def enddate(self) -> date:
        """Gets the enddate of this Subsidy.


        :return: The enddate of this Subsidy.
        :rtype: date
        """
        return self._enddate

    @enddate.setter
    def enddate(self, enddate: date):
        """Sets the enddate of this Subsidy.


        :param enddate: The enddate of this Subsidy.
        :type enddate: date
        """

        self._enddate = enddate

    @property
    def comment(self) -> str:
        """Gets the comment of this Subsidy.


        :return: The comment of this Subsidy.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment: str):
        """Sets the comment of this Subsidy.


        :param comment: The comment of this Subsidy.
        :type comment: str
        """

        self._comment = comment
