# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, real_name: str=None, email: str=None):  # noqa: E501
        """User - a model defined in Swagger

        :param username: The username of this User.  # noqa: E501
        :type username: str
        :param real_name: The real_name of this User.  # noqa: E501
        :type real_name: str
        :param email: The email of this User.  # noqa: E501
        :type email: str
        """
        self.swagger_types = {
            'username': str,
            'real_name': str,
            'email': str
        }

        self.attribute_map = {
            'username': 'username',
            'real_name': 'realName',
            'email': 'email'
        }

        self._username = username
        self._real_name = real_name
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this User.


        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this User.


        :param username: The username of this User.
        :type username: str
        """

        self._username = username

    @property
    def real_name(self) -> str:
        """Gets the real_name of this User.


        :return: The real_name of this User.
        :rtype: str
        """
        return self._real_name

    @real_name.setter
    def real_name(self, real_name: str):
        """Sets the real_name of this User.


        :param real_name: The real_name of this User.
        :type real_name: str
        """

        self._real_name = real_name

    @property
    def email(self) -> str:
        """Gets the email of this User.


        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this User.


        :param email: The email of this User.
        :type email: str
        """

        self._email = email
